### ISSUE TITLE
[Feature Request] SHELL-based or user-choice shebang in MadMiner created run scripts

### ISSUE THREAD

**Issue by sbrass** [diana-hep/madminer#448]
Hey guys,

I've came across following issue: 
Using the automatically generated run-scripts by MadMiner, I've found that you employ each with a `#!/bin/bash` shebang.
In principle, this is fine, but there are quite large institutes that use ZSH or CSH as default (login) shell (or just imagine an user who just does not use bash), thus, you would enforce a different environment than their login environment, i.e. all environment variables are off.
It took me quite some time, which I would have liked to spent for a better, to realize what killed my computations (i.e. the wrong setting of PATH, hence, a different Python version and so on... ) .

Could you use instead the `SHELL` environment variable to be really portable in your scripts/shebang statement (you are already using the os module, e.g. `os.environ['SHELL'])? 

Cheers,
Simon

**Comment by johannbrehmer** [comment]
Hi Simon,

thanks a lot for reporting this and the suggestion, this makes a lot of sense to me.

@Sinclert I'm curious about your thoughts on this?

Cheers,
Johann

**Comment by Sinclert** [comment]
Hi Simon, thank you for opening this issue.

My understanding is that shell script _shebangs_ are only applicable when there is no specified shell to run the script:
```sh
./my_script.sh
```

However, you can always specified a specific shell, so that the shebang gets overpassed:
```sh
/bin/bash ./my_script.sh
```

**Do you have a use case where you cannot manually launch a specific shell? If so, could you describe it?**

I think your suggestion is a good one, although I am concerned about the extreme variability of _default_ shells from system to system. An alternative approach would be to define `/bin/sh` as the default shell, and make sure all the commands in the script are POSIX compliant (which they are, for now).
