### ISSUE TITLE
Migrate CI and CD from Travis CI to GitHub Actions workflows

### ISSUE THREAD

**Issue by matthewfeickert** [diana-hep/madminer#456]
There seems to be interest in using GitHub Actions workflows for CI and CD in the future. An example of how GHA can be quite nice for automating releases to PyPI can be seen in `pylhe` and is linked in PR #455 which instigated this Issue:

> We could probably use something like this in the future. As you noticed, current CI/CD system is Travis, so... maybe open issue to keep track of the Travis <-> GHA migration? 🤷🏻‍♂️

_Originally posted by @Sinclert in https://github.com/diana-hep/madminer/pull/455#issuecomment-823564143_

**Comment by Sinclert** [comment]
I reopened this issue because it seems that the `release: [published]` trigger is not, well, triggering the [publish.yml](https://github.com/diana-hep/madminer/blob/master/.github/workflows/publish.yml) GHA workflow upon the creation of a `Pre-release` type release (I noticed now, when manually creating the [v0.8.0 release](https://github.com/diana-hep/madminer/releases/tag/0.8.0)).

@matthewfeickert maybe you know:
- Why could this happen? 
- Could it be because, at the time of the release, the GHA workflows were not defined yet?

**Comment by matthewfeickert** [comment]
@Sinclert I'm not sure. Given https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release I would have thought this should trigger, but I don't have experience using this workflow with pre-releases. This sort of workflow is how [`pylhe` publishes releases to PyPI](https://github.com/scikit-hep/pylhe/blob/d35bb3212d8b150c83527bdbf8426b93d6a2ccdd/.github/workflows/publish-package.yml#L1-L11), and we haven't had problems in the past. :?

**Comment by Sinclert** [comment]
m...m... I will leave this issue open then, so we can track what actually happens upon the next release.

**Comment by Sinclert** [comment]
> * Could it be because, at the time of the release, the GHA workflows were not defined yet?

We can now confirm that, indeed, that was the reason why the [publish.yml](https://github.com/diana-hep/madminer/blob/master/.github/workflows/publish.yml) workflow did not triggered with the `0.8.0` version pre-release. Once we did the pre-release for version `0.8.1` (where the workflow was already defined), it triggered correctly.

As a last step, we would need to fix the [PyPi-publication action](https://github.com/marketplace/actions/pypi-publish) pinned version, as the first and only run [failed](https://github.com/diana-hep/madminer/actions/runs/947066320) because of a mismatched version.

**Comment by matthewfeickert** [comment]
Glad this is working now.

> As a last step, we would need to fix the [PyPi-publication action](https://github.com/marketplace/actions/pypi-publish) pinned version, as the first and only run [failed](https://github.com/diana-hep/madminer/actions/runs/947066320) because of a mismatched version.

Yeah, version numbers don't resolve the same way as they do on PyPI, so you would have needed `pypa/gh-action-pypi-publish@v1.4.0` here 

https://github.com/diana-hep/madminer/blob/84943076d1acfa1151e3aed3c7a704d8f0c4f8bf/.github/workflows/publish.yml#L64

which you already resolved with PR #464. :)

https://github.com/diana-hep/madminer/blob/635d3745f8361f6d614a341dfda10dc15f12ae9b/.github/workflows/publish.yml#L64
